### ISSUE TITLE
Bench issue

### ISSUE THREAD

**Issue by luwes** [nextapps-de/mikado#2]
Congrats on your library! Awesome performance.

Thanks for adding Sinuous to the bench. I appreciate it!

I saw you couldn't use the `template` function, I think it's because of this custom `href` attribute on the `div` element. 
https://github.com/nextapps-de/mikado/blob/master/bench/test/sinuous/index.html#L30

`Node.cloneNode()` doesn't clone "custom" properties. I know it's an attribute but in my lib properties are set if possible. Since `href` is specific to anchor tags it's not cloned I guess.

**Comment by luwes** [comment]
This would work for example

js```
        const Row = template(() => html`
            <section data-id="${ t('id') }" data-date="${ t('date') }" data-index="${ t('index') }">
                <div class="${ t('class') }" style="padding-right: 10px;">
                    <div class="title">${ t('title') }</div>
                    <div class="content">${ t('content') }</div>
                    <div class="footer" class="show-test">${ t('footer') }</div>
                </div>
            </section>
        `);
```

**Comment by ts-thomas** [comment]
Thanks a lot. I added your suggestion, works fine. For some reason I could not get the template to run. I will remove the custom "href" tag from this test at all. It has no relevance for the benchmark. I much like the observable concept from sinuous, I definitively have to take a deeper dive into this :)

**Comment by ryansolid** [comment]
Probably not exactly the place. But something is definitely wrong with the Surplus implementation. I don't know what it is as I haven't looked into it. But give the type of tests you are doing I would expect pre-Sinuous templates, Surplus should be slotting in between domc and Sinuous. Post templates its a different story and Sinuous will likely be slightly ahead. But understanding in detail what all these libraries are doing there is something very very wrong going on.

Sinuous, Solid, and Surplus are using almost identical technology for change updates. Surplus pre-compilation can generate more efficient executed code, than Sinuous as it has to generate at runtime each iteration via HyperScript. Templates change the story since Sinuous only needs to run the less optimized code once, and then can use HTMLTemplate clone to be even more performant than Surplus. Solid just generates the Template optimized code to begin with. That's basically the core of the difference.

In any Benchmark with repeated iterations though Solid's initial advantage over Sinuous Templates will mostly disappear in over time, since the DOM code is very similar after the first insert. Sinuous' Templates have one advantage since they know their intent the reactivity system can be lightened slightly and directly bound (more like what you are doing with Mikado) so it is possible that for small updates Sinuous Templates can be faster after the fact. However, that benefit also diminishes and produces more complicated patterns the deeper you nest the hierarchy, and in cases where your data needs binding to multiple different template can actually be an overhead in comparison. However even in those cases it's unlikely that overhead has any significant impact compared to the advantage of more optimized DOM operations. So I'm talking a handful of milliseconds over 1000s of iterations etc..

**Comment by ts-thomas** [comment]
@ryansolid Thanks a lot for this hint. I proofed this test implementation from surplus and found an issue. This benchmark is now fixed and performs significantly better.
