### ISSUE TITLE
view.data(node) returns undefined on event handler

### ISSUE THREAD

**Issue by agrinei** [nextapps-de/mikado#45]
I'm trying to make a sample work but I've found an issue. If I don't call view.refresh() or view.render() twice, then view.data(node) returns undefined:

Code sample below:

`

	<div id="app"></div>
	<template id="user-list">
		<div>
			<p>{{data.name}}</p>
			  <ul for="data.roles">
				<li class="{{data.active ? 'on' : 'off'}}" click="clicked">{{data.description}}</li>
			  </ul>
		</div>
	</template>

	<script src="https://rawcdn.githack.com/nextapps-de/mikado/master/dist/mikado.es5.js"></script>
	<script>
	
		var users = [
		  {
			name: "John",
			roles: [{description: 'data reader', active: 1}, {description: 'data writer', active: 0}, {description: 'dbo', active: 0}]
		  },
		  {
			name: "Anna",
			roles: [{description: 'data reader', active: 1}, {description: 'data writer', active: 1}, {description: 'dbo', active: 0}]
		  },
		  {
			name: "Thomaz",
			roles: [{description: 'data reader', active: 0}, {description: 'data writer', active: 0}, {description: 'dbo', active: 1}]
		  }
		];
		
		 var tpl = Mikado.compile(document.getElementById("user-list"));
		 var view = Mikado(tpl, { store: true, loose: true });
		 view.route("clicked", function(node, event, self) {
			var item = view.data(node);
			console.log(item); // if we don't call view.refresh (or view.render twice) it logs 'undefined'
		 });
		 view.mount(document.getElementById('app'));
		 view.render(users);
		 //view.refresh(); // uncomment to make it work as it should ...
 
	</script>

`

**Comment by john5000** [comment]
@ts-thomas, more info:

You have to do .render() twice, after your very first render only, in order to use .data(node).

That is because the internal .create call uses .cloneNode(...) which loses the property value _data. So the .data(node) call won't work.  The problem is the cloneNode call does not include properties when making a clone (one of the problems with cloneNode). But if you call render() a second time, it does the internal .update call which adds the _data back, so then the .data(node) call will work.

**Comment by ts-thomas** [comment]
This issue should be gone in Mikado v0.8.x
