### ISSUE TITLE
what is the main diffrence beween Keyed/Non-Keyed Modes ?

### ISSUE THREAD

**Issue by Abdulrhman311** [nextapps-de/mikado#58]
**In another way what is the use of each of them ?**

**Comment by zilveer** [comment]
I would like to know this also.

regards Zilveer

**Comment by ts-thomas** [comment]
It is how template elements should be reused. If non-keyed is applied a rendered template will be reused on the next upcoming rendering step, this is also called "recycle". I keyed is applied, every template is connected to an ID (which is coming from the rendering data). In this case template elements are just reused on next rendering if the ID stays same. A strategy known as "reconciliation" comes into play in this mode, which moves template elements to a new position, accordingly to the new position in the data and also remove and create new elements.

Keyed rendering is faster but can have side-effects when using extern libraries or setting attributes directly to the nodes within the template, e.g. you manually change the style of a node which is part of a template. Then you might should use keyed rendering, because when using "recycling" the style is also applied on next rendering which then could be set on a false data item.

**Comment by zilveer** [comment]
@ts-thomas thanks for clarification. 

But now the question is how do we initiate keyed template vs non-keyed template ?

Regards Zilveer

**Comment by ts-thomas** [comment]
In the new Version 0.8.x you need just define the key in HTML on the root element `<table key="data.id">` and Mikado will automatically switch to keyed mode.
