### ISSUE TITLE
more about the principle of implementation

### ISSUE THREAD

**Issue by cbbfcd** [nextapps-de/mikado#6]
Thank you, this is a great project!! ❤️
it is even faster than the vanillajs. I am very interested about it. 
i want to know more about the principle of implementation, do you have related blogs or articles?

**Comment by s0kil** [comment]
@ts-thomas Would also be nice to see the goals for the future of this project for anyone willing to contribute.

**Comment by ts-thomas** [comment]
@s0kil I've added a short note about future plans: https://stackoverflow.com/questions/16483560/how-to-implement-dom-data-binding-in-javascript
The most important next step is getting more attention to this library. The feature-set of this project should increase in relation to its popularity.

@cbbfcd Technically there is no secret in the concept of Mikado. The performance results from the reverse engineering methodology and a wide knowledge about how Javascript will processed by a browser. It is the 4th open source library which I have made this way. And all of them delivers the best performance and usability in its class. The table of priority are always equal:
1. best overall performance (has influence on the largest target group: users of an application)
2. intuitiv, common and simple development (has influence on the 2nd largest target group: developers)
3. dependency-free which also fits into every stack (has influence on the 3rd largest target group: community)
There is a 4th group, the smallest of all, that's are the contributor of this project. This group must be subordinate to the other groups. That's why the "beautifulnes" of the codebase isn't one of the top goals. It is not possible to give all groups the same importance 
without any compromises. I will publish an article about this concept very soon.

**Comment by cbbfcd** [comment]
@ts-thomas I will try my best to get involved. the first important thing is to make it popular.
there are so many develop in china, i will try to use this repo, and understand it, so i can try to promote it.

> The performance results from the reverse engineering methodology and a wide knowledge about how Javascript will processed by a browser. 

There must be a lot of details about performance here, I will try my best to understand，
thx so much!

**Comment by s0kil** [comment]
[DEV](https://dev.to) and [Medium](https://medium.com) are great places to advertise this lib.

**Comment by cbbfcd** [comment]
> [DEV](https://dev.to) and [Medium](https://medium.com) are great places to advertise this lib.

@s0kil Github Trending? Stackoverflow & InfoQ

**Comment by ts-thomas** [comment]
@cbbfcd @s0kil I just released the new version 0.4.2 which comes with a new shared template pool. This speeds up everything to a complete new level.

About the concept: https://github.com/nextapps-de/mikado#concept-of-shared-pools
Show benchmark table: https://github.com/nextapps-de/mikado#benchmark
Run benchmark test: https://raw.githack.com/nextapps-de/mikado/master/bench/index.html

**Comment by cbbfcd** [comment]
@ts-thomas 
Very good idea 👍, the fastest must be the best, I think so! 
Whether the follow-up promotion should start from enriching its ecology?
BTW,  I am learning the structural design and code of the entire project, and I look forward to being able to participate.
