### ISSUE TITLE
Debug bundle module issue?

### ISSUE THREAD

**Issue by hsnoil** [nextapps-de/mikado#78]
I loaded up the todomvc example, did `npm update` to be sure I was on latest, and it ran fine other than an error of `learn.json` not existing.

I then swapped in app.js and rout.js from min:

```javascript
import Mikado from "../node_modules/mikado/dist/mikado.bundle.module.min.js";
```
to debug:
```javascript
import Mikado from "../node_modules/mikado/dist/mikado.bundle.module.debug.js";
```
Then did a hard reload (so it won't load from cache), and I got this error:

```
Uncaught SyntaxError: Unexpected token 'export' (at mikado.bundle.module.debug.js:1554:3)
```

**Comment by ts-thomas** [comment]
Thanks a lot for the report. The debug build wasn't resolved by the closure compiler in "simple" mode, so I switched back to full compilation instead. Also, I slightly updated the todomvc example because of the missing "learn.json" file. Make sure you use the lastest version, I've reverted the latest change to IDL properties, which needs to be supported by the todomvc example. I will add a more complex test for such properties like "checked" or "selected".

**Comment by hsnoil** [comment]
Okay, it works now, thanks!

Though it does give some warnings when you add an entry:
```
app.js:1 The template 'app|1' is a static template and should not be updated. Alternatively you can use .replace() to switch contents.
```

**Comment by ts-thomas** [comment]
I've fixed the warning detection 👍

**Comment by hsnoil** [comment]
Works fine now, thanks!
