### ISSUE TITLE
Error when rendering this template

### ISSUE THREAD

**Issue by Dan-Do** [nextapps-de/mikado#86]
Hi @ts-thomas,

I have this template
```javascript
const tpl_form_signin = Mikado.compile(`<div if="undefined!=this.state.error" class="my-2 notification danger">{{#this.state.error}}</div>`);
const view = new Mikado(tpl_form_signin);
view.mount(document.getElementById('view-signin')).render(undefined, {"error":"Fake test!"});
```
Error:
`TypeError: can't access property "mount", this.inc[0] is undefined`

If I change the template to
```javascript
const tpl_form_signin = Mikado.compile(`<div class="my-2 {{undefined!=this.state.error ? 'notification danger':'hidden'}}">{{#this.state.error}}</div></form>`);
const view = new Mikado(tpl_form_signin);
view.mount(document.getElementById('view-signin')).render(undefined, {"error":"Fake test!"});
```
Error:
`TypeError: can't access property "c", _o is undefined`

Could you please look at them?

**Comment by ts-thomas** [comment]
Please do not create your templates as string, because this `<div class="my-2 {{undefined!=this.state.error ? 'notification danger':'hidden'}}">{{#this.state.error}}</div></form>` istn't valid HTML.

Instead define your templates this way whe using the runtime compiler:
```httml
<form>
    <div class="my-2 {{ undefined != this.state.error ? 'notification danger' : 'hidden' }}">
        {{# this.state.error }}
    </div>
</form>
```
Also please read the documentation, when using `if="undefined!=this.state.error"` it creates a new template under the hood and the rule claims "every template needs to have one single outer bound" and `{{#this.state.error}}` isn't an root, because it isn't element. The proper template should look like:
```httml
<div if="undefined!=this.state.error" class="my-2 notification danger">
    <span>{{#this.state.error}}</span>
</div>
```

Also consider to use the native compiler instead of the runtime compiler, since it is the recommended way.

**Comment by Dan-Do** [comment]
Thanks Thomas, I made it.

BTW, can we set a global state of all instance? I read the code of Mikado constructor `new Mikado(template, options)`, it actually assign the state to instance `this.state = options.state || {};`
I want a global state to store something like theme, current logined user information, settings...

**Comment by Dan-Do** [comment]
I have an infinitive recursive loop in this situation:
`const view = new Mikado(tpl, { state: app_state, on: { insert: () => myInsertFunc(view,...) } }).mount(document.getElementById('my-view'));`
On `myInsertFunc` I have a render to update the loading state (ie. showing a spinning gear)
```
function myInsertFunc(view,...) {
    view.render({}, { loading: true });
    ...
}
```
The `view.render(...)` call `Mikado.add` which then call `myInsertFunc` again:
```
const callback = this.on && this.on.insert;
callback && callback(node, this);
```
How can I avoid this?
